-- ChaskaBox migration 012 — privacy-safe order status timeline.
-- Additive: does not change the orders primary key type and does not expose events directly.

create table if not exists public.order_status_events (
  id bigint generated by default as identity primary key,
  order_id text not null,
  order_number text,
  event_type text not null check (event_type in ('order_created','fulfilment_status','payment_status')),
  old_status text,
  new_status text,
  created_at timestamptz not null default now()
);

create index if not exists order_status_events_order_id_created_idx
  on public.order_status_events (order_id, created_at);

alter table public.order_status_events enable row level security;
-- Intentionally no browser policy. Service-role server APIs read this table.

create or replace function public.chaskabox_record_order_status_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  begin
    if tg_op = 'INSERT' then
      insert into public.order_status_events(order_id, order_number, event_type, new_status, created_at)
      values (new.id::text, new.order_number, 'order_created', coalesce(new.fulfilment_status, 'new'), coalesce(new.created_at, now()));

      if new.payment_status is not null then
        insert into public.order_status_events(order_id, order_number, event_type, new_status, created_at)
        values (new.id::text, new.order_number, 'payment_status', new.payment_status, coalesce(new.created_at, now()));
      end if;
    elsif tg_op = 'UPDATE' then
      if new.fulfilment_status is distinct from old.fulfilment_status then
        insert into public.order_status_events(order_id, order_number, event_type, old_status, new_status)
        values (new.id::text, new.order_number, 'fulfilment_status', old.fulfilment_status, new.fulfilment_status);
      end if;
      if new.payment_status is distinct from old.payment_status then
        insert into public.order_status_events(order_id, order_number, event_type, old_status, new_status)
        values (new.id::text, new.order_number, 'payment_status', old.payment_status, new.payment_status);
      end if;
    end if;
  exception when others then
    -- Timeline logging must never make order creation/status updates fail.
    raise warning 'chaskabox order status event write failed: %', sqlerrm;
  end;
  return new;
end;
$$;

revoke all on function public.chaskabox_record_order_status_event() from public;

drop trigger if exists chaskabox_order_status_event_insert_trigger on public.orders;
create trigger chaskabox_order_status_event_insert_trigger
after insert on public.orders
for each row execute function public.chaskabox_record_order_status_event();

drop trigger if exists chaskabox_order_status_event_update_trigger on public.orders;
create trigger chaskabox_order_status_event_update_trigger
after update of fulfilment_status, payment_status on public.orders
for each row execute function public.chaskabox_record_order_status_event();
