-- ChaskaBox migration 013 — durable owner-notification outbox.
-- The trigger is exception-safe: notification infrastructure can NEVER roll back an order.

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  status text not null default 'pending' check (status in ('pending','processing','retry','done','dead')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_outbox_ready_idx
  on public.notification_outbox (status, next_attempt_at, created_at);

alter table public.notification_outbox enable row level security;
-- Intentionally no browser policy. Only service-role jobs/admin APIs use this table.

create or replace function public.chaskabox_enqueue_order_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  begin
    insert into public.notification_outbox(order_id)
    values (new.id::text)
    on conflict (order_id) do nothing;
  exception when others then
    -- Critical contract: notification failure must not abort/rollback checkout.
    raise warning 'chaskabox notification outbox enqueue failed: %', sqlerrm;
  end;
  return new;
end;
$$;

revoke all on function public.chaskabox_enqueue_order_notification() from public;

drop trigger if exists chaskabox_notification_outbox_trigger on public.orders;
create trigger chaskabox_notification_outbox_trigger
after insert on public.orders
for each row execute function public.chaskabox_enqueue_order_notification();
