-- ChaskaBox v4: durable customer transactional notification outbox.
-- Owner new-order notifications remain in notification_outbox; customer events are
-- separated so each status/payment event has an independent dedupe key and retry state.
CREATE TABLE IF NOT EXISTS public.customer_notification_outbox (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null check (event_type in ('order_status','payment_status')),
  event_key text not null unique,
  message text not null check (length(message) between 1 and 2000),
  status text not null default 'pending' check (status in ('pending','processing','retry','done','dead')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS customer_notification_outbox_ready_idx
  ON public.customer_notification_outbox(status,next_attempt_at,created_at);
ALTER TABLE public.customer_notification_outbox ENABLE ROW LEVEL SECURITY;
-- No browser RLS policies by design. service_role/admin server paths only.
